# This is a basic workflow to help you get started with Actions

name: Hello Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-test
    
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello,World! 
      - name: Run a multi-line script
        run: |
          echo Add other actions to build
          echo test and deploy your project
      
